language: php
dist: xenial
sudo: false
matrix:
  fast_finish: true
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0
script:
  - pear run-tests tests/
  - for i in `ls tests/*.diff`; do echo $i; cat $i; done
